// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShopApp.Data;

#nullable disable

namespace ShopApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ShopApp.Models.Department", b =>
                {
                    b.Property<int>("DeptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("DEPT_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DeptId"));

                    b.Property<string>("Info")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("INFO");

                    b.Property<string>("Name")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("NAME");

                    b.HasKey("DeptId");

                    b.ToTable("Departments", (string)null);

                    b.HasData(
                        new
                        {
                            DeptId = 1,
                            Info = "Харчові товари",
                            Name = "Продукти"
                        },
                        new
                        {
                            DeptId = 2,
                            Info = "Техніка та гаджети",
                            Name = "Електроніка"
                        },
                        new
                        {
                            DeptId = 3,
                            Info = "Чоловічий та жіночий",
                            Name = "Одяг"
                        },
                        new
                        {
                            DeptId = 4,
                            Info = "Засоби для дому",
                            Name = "Побутхімія"
                        },
                        new
                        {
                            DeptId = 5,
                            Info = "Офісні та шкільні",
                            Name = "Канцтовари"
                        });
                });

            modelBuilder.Entity("ShopApp.Models.Good", b =>
                {
                    b.Property<int>("GoodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("GOOD_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GoodId"));

                    b.Property<int?>("DeptId")
                        .HasColumnType("int")
                        .HasColumnName("DEPT_ID");

                    b.Property<string>("Description")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("DESCRIPTION");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("NAME");

                    b.Property<double?>("Price")
                        .HasColumnType("float")
                        .HasColumnName("PRICE");

                    b.Property<string>("Producer")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("PRODUCER");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("QUANTITY");

                    b.HasKey("GoodId");

                    b.HasIndex("DeptId");

                    b.ToTable("Goods", (string)null);

                    b.HasData(
                        new
                        {
                            GoodId = 1,
                            DeptId = 1,
                            Description = "Молоко 2.5%, 1л",
                            Name = "Молоко",
                            Price = 28.5,
                            Producer = "Галичина",
                            Quantity = 120
                        },
                        new
                        {
                            GoodId = 2,
                            DeptId = 1,
                            Description = "Житній хліб 400г",
                            Name = "Хліб чорний",
                            Price = 22.0,
                            Producer = "Київхліб",
                            Quantity = 80
                        },
                        new
                        {
                            GoodId = 3,
                            DeptId = 2,
                            Description = "Бездротові BT 5.0",
                            Name = "Навушники",
                            Price = 850.0,
                            Producer = "Samsung",
                            Quantity = 15
                        },
                        new
                        {
                            GoodId = 4,
                            DeptId = 3,
                            Description = "Бавовна 100%, XL",
                            Name = "Футболка",
                            Price = 299.0,
                            Producer = "H&M",
                            Quantity = 40
                        },
                        new
                        {
                            GoodId = 5,
                            DeptId = 4,
                            Description = "Автомат 1.5 кг",
                            Name = "Порошок",
                            Price = 145.0,
                            Producer = "Tide",
                            Quantity = 55
                        },
                        new
                        {
                            GoodId = 6,
                            DeptId = 5,
                            Description = "96 аркушів, клітинка",
                            Name = "Зошит",
                            Price = 35.0,
                            Producer = "Buromax",
                            Quantity = 200
                        });
                });

            modelBuilder.Entity("ShopApp.Models.Sale", b =>
                {
                    b.Property<int>("SaleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SALE_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SaleId"));

                    b.Property<int>("CheckNo")
                        .HasColumnType("int")
                        .HasColumnName("CHECK_NO");

                    b.Property<DateTime>("DateSale")
                        .HasColumnType("date")
                        .HasColumnName("DATE_SALE");

                    b.Property<int>("GoodId")
                        .HasColumnType("int")
                        .HasColumnName("GOOD_ID");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("QUANTITY");

                    b.HasKey("SaleId");

                    b.HasIndex("GoodId");

                    b.ToTable("Sales", (string)null);

                    b.HasData(
                        new
                        {
                            SaleId = 1,
                            CheckNo = 1001,
                            DateSale = new DateTime(2024, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GoodId = 1,
                            Quantity = 3
                        },
                        new
                        {
                            SaleId = 2,
                            CheckNo = 1001,
                            DateSale = new DateTime(2024, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GoodId = 2,
                            Quantity = 2
                        },
                        new
                        {
                            SaleId = 3,
                            CheckNo = 1002,
                            DateSale = new DateTime(2024, 1, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GoodId = 3,
                            Quantity = 1
                        },
                        new
                        {
                            SaleId = 4,
                            CheckNo = 1003,
                            DateSale = new DateTime(2024, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GoodId = 4,
                            Quantity = 2
                        },
                        new
                        {
                            SaleId = 5,
                            CheckNo = 1003,
                            DateSale = new DateTime(2024, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GoodId = 5,
                            Quantity = 1
                        },
                        new
                        {
                            SaleId = 6,
                            CheckNo = 1004,
                            DateSale = new DateTime(2024, 1, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GoodId = 6,
                            Quantity = 5
                        });
                });

            modelBuilder.Entity("ShopApp.Models.Good", b =>
                {
                    b.HasOne("ShopApp.Models.Department", "Department")
                        .WithMany("Goods")
                        .HasForeignKey("DeptId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Department");
                });

            modelBuilder.Entity("ShopApp.Models.Sale", b =>
                {
                    b.HasOne("ShopApp.Models.Good", "Good")
                        .WithMany("Sales")
                        .HasForeignKey("GoodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Good");
                });

            modelBuilder.Entity("ShopApp.Models.Department", b =>
                {
                    b.Navigation("Goods");
                });

            modelBuilder.Entity("ShopApp.Models.Good", b =>
                {
                    b.Navigation("Sales");
                });
#pragma warning restore 612, 618
        }
    }
}
